/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutosDAO;
import Model.Produtos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Moura
 */
public class TelaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCaixa
     */
    public void listar(){
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listar();
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
            });
        }
    }
    
    public TelaCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_geral = new javax.swing.JTabbedPane();
        painel_caixa = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtQuant2 = new javax.swing.JTextArea();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPreco2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtNome2 = new javax.swing.JTextArea();
        txtCpf = new javax.swing.JFormattedTextField();
        txtContato = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        painel_caixa1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtQuant4 = new javax.swing.JTextArea();
        txtTotal1 = new javax.swing.JTextField();
        btnAdicionar2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        txtCod1 = new javax.swing.JTextField();
        btnFinalizar1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtPreco3 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtNome3 = new javax.swing.JTextArea();
        txtCpf2 = new javax.swing.JFormattedTextField();
        txtContato1 = new javax.swing.JFormattedTextField();
        btnAdicionar3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtQuant5 = new javax.swing.JTextField();
        txtQuant = new javax.swing.JTextField();
        btnAdicionar4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        painel_consulta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        painel_caixa.setLayout(null);

        txtQuant2.setColumns(20);
        txtQuant2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtQuant2.setLineWrap(true);
        txtQuant2.setRows(5);
        jScrollPane4.setViewportView(txtQuant2);

        painel_caixa.add(jScrollPane4);
        jScrollPane4.setBounds(220, 230, 170, 250);

        txtTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        painel_caixa.add(txtTotal);
        txtTotal.setBounds(600, 270, 170, 90);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("TOTAL:");
        painel_caixa.add(jLabel3);
        jLabel3.setBounds(650, 250, 70, 14);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("PREÇO");
        painel_caixa.add(jLabel1);
        jLabel1.setBounds(450, 200, 70, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("NOME");
        painel_caixa.add(jLabel4);
        jLabel4.setBounds(90, 210, 70, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("QUANTIDADE");
        painel_caixa.add(jLabel5);
        jLabel5.setBounds(240, 210, 140, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("QUANTIDADE:");
        painel_caixa.add(jLabel6);
        jLabel6.setBounds(370, 120, 80, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("NOME:");
        painel_caixa.add(jLabel7);
        jLabel7.setBounds(30, 40, 40, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("CPF:");
        painel_caixa.add(jLabel8);
        jLabel8.setBounds(40, 80, 30, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("CONTATO:");
        painel_caixa.add(jLabel9);
        jLabel9.setBounds(10, 120, 60, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("PRODUTO:");
        painel_caixa.add(jLabel10);
        jLabel10.setBounds(390, 80, 60, 15);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        painel_caixa.add(txtPreco);
        txtPreco.setBounds(460, 160, 190, 20);
        painel_caixa.add(txtProduto);
        txtProduto.setBounds(460, 80, 190, 20);

        txtCod.setEditable(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        painel_caixa.add(txtCod);
        txtCod.setBounds(460, 40, 190, 20);

        btnFinalizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFinalizar.setText("FINALIZAR PAGAMENTO");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        painel_caixa.add(btnFinalizar);
        btnFinalizar.setBounds(600, 390, 170, 70);

        txtPreco2.setColumns(20);
        txtPreco2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPreco2.setLineWrap(true);
        txtPreco2.setRows(5);
        jScrollPane5.setViewportView(txtPreco2);

        painel_caixa.add(jScrollPane5);
        jScrollPane5.setBounds(400, 230, 170, 250);

        txtNome2.setColumns(20);
        txtNome2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome2.setLineWrap(true);
        txtNome2.setRows(5);
        jScrollPane6.setViewportView(txtNome2);

        painel_caixa.add(jScrollPane6);
        jScrollPane6.setBounds(40, 230, 170, 250);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        painel_caixa.add(txtCpf);
        txtCpf.setBounds(80, 80, 210, 20);

        try {
            txtContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel_caixa.add(txtContato);
        txtContato.setBounds(80, 120, 210, 20);

        btnLimpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painel_caixa.add(btnLimpar);
        btnLimpar.setBounds(670, 120, 130, 50);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("PREÇO:");
        painel_caixa.add(jLabel12);
        jLabel12.setBounds(400, 160, 43, 15);

        painel_caixa1.setLayout(null);

        txtQuant4.setColumns(20);
        txtQuant4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtQuant4.setLineWrap(true);
        txtQuant4.setRows(5);
        jScrollPane7.setViewportView(txtQuant4);

        painel_caixa1.add(jScrollPane7);
        jScrollPane7.setBounds(220, 230, 170, 250);
        painel_caixa1.add(txtTotal1);
        txtTotal1.setBounds(600, 270, 170, 90);

        btnAdicionar2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar2.setText("PREENCHER");
        btnAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar2ActionPerformed(evt);
            }
        });
        painel_caixa1.add(btnAdicionar2);
        btnAdicionar2.setBounds(600, 40, 110, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("TOTAL:");
        painel_caixa1.add(jLabel13);
        jLabel13.setBounds(650, 250, 70, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("PREÇO");
        painel_caixa1.add(jLabel14);
        jLabel14.setBounds(450, 200, 70, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("NOME");
        painel_caixa1.add(jLabel15);
        jLabel15.setBounds(90, 210, 70, 14);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("QUANTIDADE");
        painel_caixa1.add(jLabel16);
        jLabel16.setBounds(240, 210, 140, 14);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("PREÇO:");
        painel_caixa1.add(jLabel17);
        jLabel17.setBounds(470, 150, 50, 15);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("NOME:");
        painel_caixa1.add(jLabel18);
        jLabel18.setBounds(80, 40, 40, 15);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("CPF:");
        painel_caixa1.add(jLabel19);
        jLabel19.setBounds(90, 80, 30, 15);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("CONTATO:");
        painel_caixa1.add(jLabel20);
        jLabel20.setBounds(60, 120, 60, 15);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("CÓDIGO DO PRODUTO:");
        painel_caixa1.add(jLabel21);
        jLabel21.setBounds(390, 40, 140, 15);
        painel_caixa1.add(txtPreco1);
        txtPreco1.setBounds(530, 150, 210, 20);
        painel_caixa1.add(txtNome1);
        txtNome1.setBounds(130, 40, 210, 20);

        txtCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod1ActionPerformed(evt);
            }
        });
        painel_caixa1.add(txtCod1);
        txtCod1.setBounds(530, 40, 60, 20);

        btnFinalizar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFinalizar1.setText("FINALIZAR PAGAMENTO");
        painel_caixa1.add(btnFinalizar1);
        btnFinalizar1.setBounds(600, 390, 170, 70);

        txtPreco3.setColumns(20);
        txtPreco3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPreco3.setLineWrap(true);
        txtPreco3.setRows(5);
        jScrollPane8.setViewportView(txtPreco3);

        painel_caixa1.add(jScrollPane8);
        jScrollPane8.setBounds(400, 230, 170, 250);

        txtNome3.setColumns(20);
        txtNome3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome3.setLineWrap(true);
        txtNome3.setRows(5);
        jScrollPane9.setViewportView(txtNome3);

        painel_caixa1.add(jScrollPane9);
        jScrollPane9.setBounds(40, 230, 170, 250);

        try {
            txtCpf2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel_caixa1.add(txtCpf2);
        txtCpf2.setBounds(130, 80, 210, 20);

        try {
            txtContato1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel_caixa1.add(txtContato1);
        txtContato1.setBounds(130, 120, 210, 20);

        btnAdicionar3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar3.setText("ADICIONAR");
        painel_caixa1.add(btnAdicionar3);
        btnAdicionar3.setBounds(600, 190, 140, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("QUANTIDADE:");
        painel_caixa1.add(jLabel22);
        jLabel22.setBounds(440, 110, 80, 15);
        painel_caixa1.add(txtQuant5);
        txtQuant5.setBounds(530, 110, 210, 20);

        painel_caixa.add(painel_caixa1);
        painel_caixa1.setBounds(0, 0, 0, 0);
        painel_caixa.add(txtQuant);
        txtQuant.setBounds(460, 120, 190, 20);

        btnAdicionar4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar4.setText("ADICIONAR");
        btnAdicionar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar4ActionPerformed(evt);
            }
        });
        painel_caixa.add(btnAdicionar4);
        btnAdicionar4.setBounds(670, 40, 130, 50);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("CÓDIGO DO PRODUTO:");
        painel_caixa.add(jLabel11);
        jLabel11.setBounds(320, 40, 140, 15);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        painel_caixa.add(txtNome);
        txtNome.setBounds(80, 40, 210, 20);

        painel_geral.addTab("CAIXA", painel_caixa);

        painel_consulta.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NOME:");
        painel_consulta.add(jLabel2);
        jLabel2.setBounds(20, 40, 40, 15);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painel_consulta.add(txtPesquisar);
        txtPesquisar.setBounds(60, 40, 200, 20);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painel_consulta.add(btnPesquisar);
        btnPesquisar.setBounds(280, 40, 120, 23);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "PREÇO"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        painel_consulta.add(jScrollPane2);
        jScrollPane2.setBounds(0, 90, 810, 390);

        painel_geral.addTab("CONSULTAR PRODUTOS", painel_consulta);

        getContentPane().add(painel_geral);
        painel_geral.setBounds(0, 0, 820, 510);

        setSize(new java.awt.Dimension(841, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nome = "%"+txtPesquisar.getText()+"%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.filtrar(nome);
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
                
            });
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        String nome = "%"+txtPesquisar.getText()+"%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.filtrar(nome);
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
                
            });
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        painel_geral.setSelectedIndex(0);
        txtCod.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtProduto.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        txtPreco.setText(tabela.getValueAt(tabela.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btnAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionar2ActionPerformed

    private void txtCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod1ActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Controller.funcoes_DAO.limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnAdicionar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar4ActionPerformed
        Controller.funcoes_DAO.adicionar();
    }//GEN-LAST:event_btnAdicionar4ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar2;
    private javax.swing.JButton btnAdicionar3;
    private javax.swing.JButton btnAdicionar4;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel painel_caixa;
    private javax.swing.JPanel painel_caixa1;
    private javax.swing.JPanel painel_consulta;
    private javax.swing.JTabbedPane painel_geral;
    private javax.swing.JTable tabela;
    public static javax.swing.JTextField txtCod;
    public static javax.swing.JTextField txtCod1;
    public static javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtContato1;
    public static javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCpf2;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtNome1;
    public static javax.swing.JTextArea txtNome2;
    public static javax.swing.JTextArea txtNome3;
    public static javax.swing.JTextField txtPesquisar;
    public static javax.swing.JTextField txtPreco;
    public static javax.swing.JTextField txtPreco1;
    public static javax.swing.JTextArea txtPreco2;
    public static javax.swing.JTextArea txtPreco3;
    public static javax.swing.JTextField txtProduto;
    public static javax.swing.JTextField txtQuant;
    public static javax.swing.JTextArea txtQuant2;
    public static javax.swing.JTextArea txtQuant4;
    public static javax.swing.JTextField txtQuant5;
    public static javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtTotal1;
    // End of variables declaration//GEN-END:variables
}
